<a href="https://colab.research.google.com/github/madhavaai/Data-science/blob/main/DS2P1L1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
path_1 = "/content/mexico-real-estate-1.csv"

In [75]:
import pandas as pd

In [77]:
df1=pd.read_csv(path_1)
df1

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.56,-99.23,150.00,"$67,965.56"
1,house,Nuevo León,25.69,-100.20,186.00,"$63,223.78"
2,apartment,Guerrero,16.77,-99.76,82.00,"$84,298.37"
3,apartment,Guerrero,16.83,-99.91,150.00,"$94,308.80"
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.00,"$94,835.67"
...,...,...,...,...,...,...
695,house,Morelos,NaN,NaN,310.00,"$237,089.17"
696,house,Yucatán,21.05,-89.56,334.00,"$137,017.34"
697,house,Yucatán,21.34,-89.26,130.00,"$110,404.35"
698,apartment,Nuevo León,NaN,NaN,155.00,"$184,446.42"
699,house,Querétaro,20.59,-100.42,106.00,"$56,637.97"

In [78]:
df1.head()

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.56,-99.23,150.00,"$67,965.56"
1,house,Nuevo León,25.69,-100.20,186.00,"$63,223.78"
2,apartment,Guerrero,16.77,-99.76,82.00,"$84,298.37"
3,apartment,Guerrero,16.83,-99.91,150.00,"$94,308.80"
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.00,"$94,835.67"

In [80]:
df1.shape

(700, 6)

In [81]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  700 non-null    object
 1   state          700 non-null    object
 2   lat            583 non-null    float64
 3   lon            583 non-null    float64
 4   area_m2        700 non-null    float64
 5   price_usd      700 non-null    object
dtypes: float64(3), object(3)
memory usage: 32.9+ KB

In [82]:
df1.dtypes

property_type     object
state             object
lat              float64
lon              float64
area_m2          float64
price_usd         object
dtype: object

In [83]:
df1.isnull().sum()

property_type      0
state              0
lat              117
lon              117
area_m2            0
price_usd          0
dtype: int64

In [85]:
df1 = df1.dropna()
df1

    property_type             state   lat     lon  area_m2    price_usd
0           house  Estado de México 19.56  -99.23   150.00   $67,965.56
1           house        Nuevo León 25.69 -100.20   186.00   $63,223.78
2       apartment          Guerrero 16.77  -99.76    82.00   $84,298.37
3       apartment          Guerrero 16.83  -99.91   150.00   $94,308.80
5           house           Yucatán 21.05  -89.54   205.00  $105,191.37
..            ...               ...   ...     ...      ...          ...
693         house            Puebla 19.05  -98.28   198.00  $115,910.26
694     apartment  Distrito Federal 19.31  -99.17    70.00   $77,572.89
696         house           Yucatán 21.05  -89.56   334.00  $137,017.34
697         house           Yucatán 21.34  -89.26   130.00  $110,404.35
699         house         Querétaro 20.59 -100.42   106.00   $56,637.97

[583 rows x 6 columns]

In [86]:
df1.shape

(583, 6)

In [87]:
df1=df1.assign(
        price_usd = lambda x: x["price_usd"]
                          .str.replace("$", "", regex=False)
                          .str.replace(",", "", regex=False)
                          .astype(float)
    )
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 583 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  583 non-null    object
 1   state          583 non-null    object
 2   lat            583 non-null    float64
 3   lon            583 non-null    float64
 4   area_m2        583 non-null    float64
 5   price_usd      583 non-null    float64
dtypes: float64(4), object(2)
memory usage: 31.9+ KB

In [88]:
path_2 = "/content/mexico-real-estate-2.csv"

In [89]:
path_3 = "/content/mexico-real-estate-3.csv"

In [90]:
df2 = pd.read_csv("/content/mexico-real-estate-2.csv")
df2

    property_type             state   lat     lon  area_m2    price_mxn
0       apartment        Nuevo León 25.72 -100.35    72.00 1,300,000.00
1       apartment            Puebla   NaN     NaN   190.00 2,500,000.00
2           house           Morelos 23.63 -102.55   360.00 5,300,000.00
3           house           Morelos   NaN     NaN    76.00   820,000.00
4           house            Puebla   NaN     NaN   200.00 1,100,000.00
..            ...               ...   ...     ...      ...          ...
695         house           Morelos 18.92  -98.96   140.00 1,450,000.00
696         house  Distrito Federal 19.47  -99.15   190.00 1,943,000.00
697         house  Estado de México 19.23  -99.56   115.00 2,100,000.00
698         house            Puebla 18.92  -98.43    90.00   890,000.00
699         house           Yucatán 21.08  -89.52   185.00 1,695,000.00

[700 rows x 6 columns]

In [91]:
df3 = pd.read_csv("/content/mexico-real-estate-3.csv")
df3

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.00,"48,550.59"
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.00,"168,636.73"
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.00,"86,932.69"
3,house,|México|Morelos|Temixco|Burgos Bugambilias|,NaN,275.00,"263,432.41"
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.00,"68,508.67"
...,...,...,...,...,...
695,house,|México|Jalisco|Tlajomulco de Zúñiga|Tlajomulc...,"20.532264,-103.484418",175.00,"121,178.91"
696,house,|México|Morelos|Jiutepec|,"18.9289862,-99.1802147",100.00,"47,417.83"
697,house,|México|Yucatán|Mérida|,"21.0284038368,-89.6530058049",81.00,"39,524.23"
698,house,|México|San Luis Potosí|San Luis Potosí|,"22.11830417,-101.0321938992",360.00,"245,050.24"
699,house,|México|Estado de México|Toluca|Metepec|,"19.233201,-99.558519",115.00,"110,667.85"

In [93]:
df2 = (df2
     # Create "price_usd" column (19 pesos to the dollar in 2014)
    .assign(price_usd = lambda x: x["price_mxn"].div(19))

    # Drop "price_mxn" column
    .drop(columns=["price_mxn"])

    # Drop null values
    .dropna()
)

# Print object type, shape, and head
print(f"df2 type: {type(df2)}")
print(f"df2 shape: {df2.shape}")
df2.head()

df2 type: <class 'pandas.core.frame.DataFrame'>
df2 shape: (571, 6)

  property_type             state   lat     lon  area_m2  price_usd
0     apartment        Nuevo León 25.72 -100.35    72.00  68,421.05
2         house           Morelos 23.63 -102.55   360.00 278,947.37
6     apartment  Estado de México 19.27  -99.57    85.00  65,789.47
7         house   San Luis Potosí 22.14 -101.00   158.00 111,578.95
8     apartment  Distrito Federal 19.39  -99.13    65.00  39,904.74

In [94]:
df3.head()

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.00,"48,550.59"
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.00,"168,636.73"
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.00,"86,932.69"
3,house,|México|Morelos|Temixco|Burgos Bugambilias|,NaN,275.00,"263,432.41"
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.00,"68,508.67"

In [97]:
df3["lat-lon"] .head()

0       19.52589,-99.151703
1    19.2640539,-99.5727534
2      19.268629,-99.671722
3                       NaN
4      19.511938,-96.871956
Name: lat-lon, dtype: object

In [99]:
df3["lat-lon"].str.split(",", expand=True).head()

            0            1
0    19.52589   -99.151703
1  19.2640539  -99.5727534
2   19.268629   -99.671722
3         NaN          NaN
4   19.511938   -96.871956

In [100]:
(
    df3
    ["lat-lon"]
    .str.split(",", expand=True)[0]
    .astype(float)
    .head()
)

0   19.53
1   19.26
2   19.27
3     NaN
4   19.51
Name: 0, dtype: float64

In [101]:
(
    df3
    ["place_with_parent_names"]
    .head()
)

0    |México|Distrito Federal|Gustavo A. Madero|Acu...
1             |México|Estado de México|Toluca|Metepec|
2    |México|Estado de México|Toluca|Toluca de Lerd...
3          |México|Morelos|Temixco|Burgos Bugambilias|
4    |México|Veracruz de Ignacio de la Llave|Veracruz|
Name: place_with_parent_names, dtype: object

In [102]:
(
    df3
    ["place_with_parent_names"]
    .str.split("|", expand=True)
    .head()
)

,0,1,2,3,4,5,6
0,,México,Distrito Federal,Gustavo A. Madero,Acueducto de Guadalupe,,None
1,,México,Estado de México,Toluca,Metepec,,None
2,,México,Estado de México,Toluca,Toluca de Lerdo,Ocho Cedros,
3,,México,Morelos,Temixco,Burgos Bugambilias,,None
4,,México,Veracruz de Ignacio de la Llave,Veracruz,,None,None

In [103]:
# cleaning process using method chaining
df3 = (
    df3
    # Drop null values from df3
    .dropna()
    # Create "lat" and "lon" columns for df3
    .assign(lat=lambda x: x["lat-lon"]
                .str.split(",", expand=True)[0]
                .astype(float),
            lon=lambda x: x["lat-lon"]
                .str.split(",", expand=True)[1]
                .astype(float),
            # Create "state" column for df3
            state=lambda x: x["place_with_parent_names"]
            .str.split("|", expand=True)[2]
           )

    # Drop "place_with_parent_names" and "lat-lon" from df3
    .drop(columns=["place_with_parent_names", "lat-lon"])


)

In [104]:
# Check if all column sets are identical
columns_match = set(df1) == set(df2) == set(df3)

if columns_match:
    print("✅ All DataFrames have the same columns.")
else:
    print("❌ Column mismatch detected!")
    # Optional: See the difference
    print("df1 vs df2 diff:", set(df1.columns) ^ set(df2.columns))
    print("df2 vs df3 diff:", set(df2.columns) ^ set(df3.columns))

✅ All DataFrames have the same columns.

In [105]:
df = pd.concat([df1, df2, df3], ignore_index=True)

# Verify the result
print(f"Combined Shape: {df.shape}")
df.head()

Combined Shape: (1736, 6)

  property_type             state   lat     lon  area_m2  price_usd
0         house  Estado de México 19.56  -99.23   150.00  67,965.56
1         house        Nuevo León 25.69 -100.20   186.00  63,223.78
2     apartment          Guerrero 16.77  -99.76    82.00  84,298.37
3     apartment          Guerrero 16.83  -99.91   150.00  94,308.80
4         house           Yucatán 21.05  -89.54   205.00 105,191.37

In [106]:
df.to_csv("/content/mexico-real-estate-combined-clean.csv", index=False)

In [108]:
summary = df[["price_usd", "area_m2"]].describe()


summary

       price_usd  area_m2
count   1,736.00 1,736.00
mean  115,331.98   170.26
std    65,426.17    80.59
min    33,157.89    60.00
25%    65,789.47   101.75
50%    99,262.13   156.00
75%   150,846.66   220.00
max   326,733.66   385.00